# Form implementation generated from reading ui file 'main_window.ui'

from PyQt6 import QtCore, QtGui, QtWidgets
from app.constants import TTS_VOICES
from app.controller.main_window_controller import MainWindowController
import app.ui.main_window_qrc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow, music_player_service, tts_service, parser):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 640))
        MainWindow.setMaximumSize(QtCore.QSize(800, 640))

        # Disable the maximize button
        MainWindow.setWindowFlags(QtCore.Qt.WindowType.Window | QtCore.Qt.WindowType.CustomizeWindowHint | QtCore.Qt.WindowType.WindowMinimizeButtonHint | QtCore.Qt.WindowType.WindowCloseButtonHint)

        self.widget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(800, 600))
        self.widget.setMaximumSize(QtCore.QSize(800, 600))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(400, 600))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout.addWidget(self.plainTextEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(parent=self.widget)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 190, 371, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 6, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playMediaButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.playMediaButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/play_button/play.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off
        )
        self.playMediaButton.setIcon(icon)
        self.playMediaButton.setIconSize(QtCore.QSize(16, 16))
        self.playMediaButton.setObjectName("playMediaButton")
        self.horizontalLayout_2.addWidget(self.playMediaButton)
        self.horizontalSlider = QtWidgets.QSlider(parent=self.horizontalLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 260, 371, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.playButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout_4.addWidget(self.playButton)
        self.streamButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.streamButton.setObjectName("streamButton")
        self.horizontalLayout_4.addWidget(self.streamButton)
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(0, 230, 372, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(TTS_VOICES)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.uploadButton = QtWidgets.QPushButton(parent=self.widget)
        self.uploadButton.setMinimumSize(QtCore.QSize(0, 40))
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout.addWidget(self.uploadButton)
        self.convertButton = QtWidgets.QPushButton(parent=self.widget)
        self.convertButton.setMinimumSize(QtCore.QSize(0, 40))
        self.convertButton.setObjectName("convertButton")
        self.verticalLayout.addWidget(self.convertButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.widget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 40))
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.openAction = QtGui.QAction(parent=MainWindow)
        self.openAction.setObjectName("openAction")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.saveAction = QtGui.QAction(parent=MainWindow)
        self.saveAction.setObjectName("saveAction")
        self.actionExit = QtGui.QAction(parent=MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.openAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.saveAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.music_player_service = music_player_service
        self.tts_service = tts_service
        self.parser = parser
        self.controler = MainWindowController(self,music_player_service, tts_service, parser)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "abook convertor"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.streamButton.setText(_translate("MainWindow", "Stream"))
        self.uploadButton.setText(_translate("MainWindow", "Upload E-Book"))
        self.convertButton.setText(_translate("MainWindow", "Convert to audio-book"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.openAction.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.saveAction.setText(_translate("MainWindow", "Save..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
